{% set name = "pypika-tortoise" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f0040229f99c0052efa1f74aefe0f8a66db77472222001a980ecbad1c1c502d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - pypika
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/pypika-tortoise
  summary: Forked from pypika and streamline just for tortoise-orm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
