{% set name = "pypika-tortoise" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f0fbc9e0c3ddc33118a5be69907428863849df60788e125edef1f46a6261d63b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0

test:
  imports:
    - pypika
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/pypika-tortoise
  summary: Forked from pypika and streamline just for tortoise-orm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
