{% set name = "pypika-tortoise" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypika-tortoise-{{ version }}.tar.gz
  sha256: d802868f479a708e3263724c7b5719a26ad79399b2a70cea065f4a4cadbebf36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - pypika
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/pypika-tortoise
  summary: Forked from pypika and streamline just for tortoise-orm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
