{% set name = "pypika-tortoise" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypika-tortoise-{{ version }}.tar.gz
  sha256: 2e2f747bfc645a25e097485651278cd7d920b709686ce54e43387ba1c9294048

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - pypika
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/pypika-tortoise
  summary: Forked from pypika and streamline just for tortoise-orm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
