schema_version: 1

context:
  name: pypika-tortoise
  version: 0.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 3899e45b59b506c5b2a83232094437dc63bd8cccf754123f0b48f847931cdc8c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pypika_tortoise
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Forked from pypika and streamline just for tortoise-orm
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/tortoise/pypika-tortoise

extra:
  recipe-maintainers:
    - thewchan
